config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: { omniauth_callbacks: 'users/omniauth_callbacks' }
  root to: "pages#home"
  resources :companies
  resources :projects do
    get 'newstudy', on: :collection, action: 'newstudy'
    get 'newsingle', on: :collection, action: 'newsingle'
    get 'newmulti', on: :collection, action: 'newmulti'
    get 'newleadgen', on: :collection, action: 'newleadgen'
  end

  get "client", to: "pages#dashboardclient"
  get "client/projects", to: "projects#clientprojects"



  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
end

app/views/shared/_flashes.html.erb
<% if notice %>
  <div class="alert alert-info alert-dismissible fade show m-1" role="alert">
    <%= notice %>
    <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close">
    </button>
  </div>
<% end %>
<% if alert %>
  <div class="alert alert-warning alert-dismissible fade show m-1" role="alert">
    <%= alert %>
    <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close">
    </button>
  </div>
<% end %>

app/views/shared/_navbar.html.erb
<div class="navbar navbar-expand-sm navbar-light navbar-lewagon">
  <div class="container-fluid">
    <%= link_to "#", class: "navbar-brand" do %>
      <%= image_tag "https://raw.githubusercontent.com/lewagon/fullstack-images/master/uikit/logo.png" %>
    <% end %>

    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>

    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav me-auto">
        <% if user_signed_in? %>
          <li class="nav-item active">
            <%= link_to "Home", "#", class: "nav-link" %>
          </li>
          <li class="nav-item">
            <%= link_to "Messages", "#", class: "nav-link" %>
          </li>
          <li class="nav-item dropdown">
            <%= image_tag "https://kitt.lewagon.com/placeholder/users/ssaunier", class: "avatar dropdown-toggle", id: "navbarDropdown", data: { bs_toggle: "dropdown" }, 'aria-haspopup': true, 'aria-expanded': false %>
            <div class="dropdown-menu dropdown-menu-end" aria-labelledby="navbarDropdown">
              <%= link_to "Action", "#", class: "dropdown-item" %>
              <%= link_to "Another action", "#", class: "dropdown-item" %>
              <%= link_to "Log out", destroy_user_session_path, data: {turbo_method: :delete}, class: "dropdown-item" %>
            </div>
          </li>
        <% else %>
          <li class="nav-item">
            <%= link_to "Login", new_user_session_path, class: "nav-link" %>
          </li>
        <% end %>
      </ul>
    </div>
  </div>
</div>

app/views/shared/_navbar2.html.erb
<!-- Boxicons CDN Link -->
<link href='https://unpkg.com/boxicons@2.0.7/css/boxicons.min.css' rel='stylesheet'>

<div class="sidebar" id="desktop-nav">
  <div class="logo-details">

     <%# <i class='bx bxl-c-plus-plus icon'></i> %>
      <div class="logo_name"><%= image_tag("logo", size: "150", id: "logo" ) %></div>
      <i class='bx bx-menu' id="btn" ></i>
  </div>
  <ul class="nav-list">
    <%# <li>
        <i class='bx bx-search' ></i>
      <input type="text" placeholder="Search...">
      <span class="tooltip">Search</span>
    </li> %>
    <li>
      <a href="#">
        <%= link_to  client_path do%>
          <i class='bx bx-grid-alt'></i>
          <span class="links_name">Dashboard</span>
        <% end %>
      </a>
      <span class="tooltip">Dashboard</span>
    </li>



  <li>
    <a href="#">
      <%= link_to  client_projects_path do%>
        <i class='bx bx-flag' ></i>
        <span class="links_name">Projects</span>
      <% end %>
    </a>
    <span class="tooltip">Projects</span>
  </li>
  <li>
    <a href="#">
      <i class='bx bx-paste' ></i>
      <span class="links_name">Received proposals</span>
    </a>
    <span class="tooltip">Received Proposals</span>
  </li>
  <li class='border-top pt-3 mt-3'>
    <a href="#">
      <i class='bx bxs-business'></i>
      <span class="links_name">Company Profile</span>
    </a>
    <span class="tooltip">Company</span>
  </li>
  <li>
    <a href="#">
      <i class='bx bx-credit-card' ></i>
      <span class="links_name">Payments</span>
    </a>
    <span class="tooltip">Payments</span>
  </li>
  <%# <li>
    <a href="#">
      <i class='bx bx-heart' ></i>
      <span class="links_name">Saved</span>
    </a>
    <span class="tooltip">Saved</span>
  </li> %>
  <li class='border-top pt-3 mt-3'>
    <a href="#">
      <i class='bx bx-user' ></i>
      <span class="links_name">My account</span>
    </a>
    <span class="tooltip">User</span>
  </li>
  <li>
    <a href="#">
      <i class='bx bx-cog' ></i>
      <span class="links_name">Setting</span>
    </a>
    <span class="tooltip">Setting</span>
  </li>
  <li class="profile">
    <div class="profile-details">
      <img src="<%= current_user.picture_url %>" alt="profileImg" id="profile-picture">
      <div class="name_job">
        <div class="name"><%= current_user.first_name + " " + current_user.last_name.first.capitalize + "." %></div>
        <div class="job"><%= current_user.company.name %></div>
      </div>
    <%= link_to destroy_user_session_path, data: { turbo_method: :delete } do %>
      <div><i class='bx bx-log-out' id="log_out" ></i></div>
    <% end %>
    </div>
  </li>
  </ul>
</div>

<%# <section class="home-section">
    <div class="text">Dashboard</div>
</section> %>

<script>
  let sidebar = document.querySelector(".sidebar");
  let closeBtn = document.querySelector("#btn");
  let searchBtn = document.querySelector(".bx-search");

  closeBtn.addEventListener("click", ()=>{
    sidebar.classList.toggle("open");
    menuBtnChange();//calling the function(optional)
  });

  searchBtn.addEventListener("click", ()=>{ // Sidebar open when you click on the search iocn
    sidebar.classList.toggle("open");
    menuBtnChange(); //calling the function(optional)
  });

  // following are the code to change sidebar button(optional)
  function menuBtnChange() {
  if(sidebar.classList.contains("open")){
    closeBtn.classList.replace("bx-menu", "bx-menu-alt-right");//replacing the iocns class
  }else {
    closeBtn.classList.replace("bx-menu-alt-right","bx-menu");//replacing the iocns class
  }
  }
</script>

app/views/shared/_navbarm.html.erb
<div id="myNav" class="overlay">
  <!--overlay close button-->
  <a href="#" class="closebtn" onclick="closeNav()">&times;</a>

  <!--overlay content -->
  <div class="overlay-content">
      <ul>
          <li><a href="#">Dashboard</a></li>
          <li><a href="#">My Proposals</a></li>
          <li><a href="#">Projects</a></li>
          <li><a href="#">Company Profile</a></li>
          <li><a href="#">My Account</a></li>
          <li><a href="#">Payments</a></li>
          <li><a href="#">Settings</a></li>
      </ul>
  </div>
</div>

    <!--overlay Open button-->
<div id="mobile-nav" class="navMenu" onclick="openNav()">&#9776;
</div>
<%# <div class="myPage">
</div> %>

<script>
  /* Open */
  function openNav(){
    document.getElementById("myNav").style.height = "100%";
  }

  // close
  function closeNav(){
    document.getElementById("myNav").style.height = "0%";
  }
</script>