config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: { omniauth_callbacks: 'users/omniauth_callbacks' }
  root to: "pages#home"
  resources :companies
  resources :projects do
    get 'newstudy', on: :collection, action: 'newstudy'
    get 'newsingle', on: :collection, action: 'newsingle'
    get 'newmulti', on: :collection, action: 'newmulti'
    get 'newleadgen', on: :collection, action: 'newleadgen'
  end

  get "client", to: "pages#dashboardclient"
  get "client/projects", to: "projects#clientprojects"



  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
end

app/models/company.rb
class Company < ApplicationRecord
  has_many :users, dependent: :nullify
  has_many :projects

  validates :name, :domain, :country, presence: true
end

app/controllers/companies_controller.rb
class CompaniesController < ApplicationController
  before_action :set_company, only: %i[show edit update destroy]

  def index
    @companies = Company.all
  end

  def show
    # authorize @company
  end

  def new
    @company = Company.new
    # authorize @company
  end

  def create

    # CREATE A CHECK TO SEE IF COMPANY ALREADY EXIST / THEN ONLY ATTRIBUTE ID TO USER ONLY

    # IF COMPANY DOESNT EXISTS THEN CREATE IT AND TTRIBUTE COMPANY ID TO USER
    @company = Company.new(company_params)

    # INSERT THE JOB TO ENRICH COMPANY
    @company.save
    current_user.company_id = @company.id
    current_user.save

    enriched_data = ComplookupJob.perform_now(@company.domain, @company.country, @company.name)

    unless enriched_data.nil?
      @company.description = enriched_data["description"]
      @company.founded = enriched_data["founded_year"]
      @company.company_size = enriched_data["company_size_on_linkedin"]
      @company.country = enriched_data["hq"]["country"]
      @company.specialities = enriched_data["specialities"]
      @company.tagline = enriched_data["tagline"]
      @company.profile_pic_url = enriched_data["profile_pic_url"]
      @company.background_cover_image_url = enriched_data["background_cover_image_url"]
      @company.save
    end

    redirect_to edit_company_path(@company)
    # authorize @company
  end

  def edit

  end

  def update
    @company.update(company_params)
    if @company.save
      redirect_to client_path
    else
      render :edit
    end
  end

  def destroy

  end

  def set_company
    @company = Company.find(params[:id])
  end

  def company_params
    params.require(:company).permit(:name, :domain, :country, :description, :founded, :company_size, :specialities, :tagline)
  end

end

app/views/companies/edit.html.erb
<div class="row justify-content-center align-items-center vh-100" id="backdrop">

  <div class="dash-card form-card mt-5">

    <h2>Edit Your Company</h2>
    <p>You can add/remove some information about your company before saving it.</p>

    <%= form_with model: @company, local: true, url: company_path(@company), method: :patch do |form| %>
      <div class="form-group mt-3">
        <%= form.label :name %>
        <%= form.text_field :name, class: "form-control" %>
      </div>

      <div class="form-group mt-3">
        <%= form.label :domain %>
        <%= form.text_field :domain, class: "form-control" %>
      </div>

      <div class="form-group mt-3">
        <%= form.label :country %>
        <%= form.text_field :country, class: "form-control" %>
      </div>

      <div class="form-group mt-3">
        <%= form.label :tagline %>
        <%= form.text_field :tagline, class: "form-control" %>
      </div>

      <div class="form-group mt-3">
        <%= form.label :description %>
        <%= form.text_area :description, class: "form-control" %>
      </div>

      <div class="form-group mt-3">
        <%= form.label :founded %>
        <%= form.text_field :founded, class: "form-control" %>
      </div>

      <div class="form-group mt-3">
        <%= form.label :company_size %>
        <%= form.text_field :company_size, class: "form-control" %>
      </div>

      <div class="form-group mt-3">
        <%= form.label :specialities %>
        <%= form.text_field :specialities, class: "form-control" %>
      </div>


      <%= form.submit "Update Company", class: "btn btn-primary mt-5" %>
    <% end %>
  </div>

</div>

app/views/companies/index.html.erb
<h1>All Companies / Admin Page</h1>

app/views/companies/new.html.erb
<div class="row justify-content-center align-items-center vh-100" id="backdrop">

  <div class="dash-card form-card mt-5">

    <h2>Your company</h2>
    <p>Tell us about your company. Enter the following elements accuratly and we will try to do the job for you by fetchign the rest online.</p>


    <%= form_with model: @company, local: true do |form| %>
      <div class="form-group mt-5">
        <%= form.label :name %>
        <%= form.text_field :name, class: "form-control" %>
      </div>

      <div class="form-group mt-5">
        <%= form.label :domain %>
        <%= form.text_field :domain, class: "form-control" %>
      </div>

      <div class="form-group mt-5">
        <%= form.label :country %>
        <%= form.text_field :country, class: "form-control" %>
      </div>

      <%= form.submit "Search Company", class: "btn btn-primary mt-5" %>
    <% end %>
  </div>

</div>

app/views/companies/show.html.erb
<h1>Company Show Page</h1>